version: '3'
services:
   nginx: 
     image: nginx
     volumes:
       - "./mynginx:/etc/nginx/conf.d"
       - "./nginxsites:/usr/share/nginx/html"
     ports:
       - 80:80
     deploy:
       replicas: 2
       update_config:
         parallelism: 2
         delay: 10s
       restart_policy:
         condition: on-failure

   qaftek:
     image: nginx
     volumes:
       - "./nginxsites/qaftek:/usr/share/nginx/html"

   alifsoft:
     image: nginx
     volumes:
       - "./nginxsites/alifsoft:/usr/share/nginx/html"

volumes:
     mynginx:
     

